name: ElytraNerf
version: ${project.version}
main: co.ignitus.elytranerf.ElytraNerf
authors: ["Ignitus Co"]
api-version: "1.13"
description: Reduce elytra speed.
website: https://ignitus.co

permissions:
  elytranerf.x:
    description: X becomes the users elytra speed